version: "3.9"

services:
  spring_tms:
    image: spring-boot-tms
    container_name: spring_tms
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - project.env
    ports:
      - "7900:7800"
      - "7901:7801"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/tms-db
      - SPRING_DATASOURCE_USERNAME=elanza48
      - SPRING_DATASOURCE_PASSWORD=elanza48
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres_db:
    image: custom-postgres
    container_name: postgres_db
    restart: unless-stopped
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - project.env
    ports:
      - 5532:5432
    environment:
      - POSTGRES_DB=tms-db
      - POSTGRES_USER=elanza48
      - POSTGRES_PASSWORD=elanza48
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    healthcheck: 
          test: ["CMD-SHELL", "pg_isready -d tms-db -U elanza48"]
          interval: 10s
          timeout: 5s
          retries: 5