version: "3.9"

# --------------- COMPOSE: ---------------
# docker-compose rm -f && \
# docker-compose build && \
# docker-compose up

services:
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_DB=tms-db
      - POSTGRES_USER=elanza48
      - POSTGRES_PASSWORD=elanza48
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: "no"
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -d tms-db -U elanza48"]
          interval: 10s
          timeout: 5s
          retries: 5
    labels:
      com.elanza48.description: "Elanza-48: Tourism Management System, Spring-boot-postgreSQL"
      org.opencontainers.image.authors: "Rajarshi Kundu <elanza48@outlook.com>"
  
  spring_service:
    image: elanza48/spring-boot-tms
    container_name: spring-tms

    env_file:
      - .env
    ports:
      - "7900:7800"
      - "7901:7801"
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: "no"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5532/tms-db
      - SPRING_DATASOURCE_USERNAME=elanza48
      - SPRING_DATASOURCE_PASSWORD=elanza48
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    labels:
      com.elanza48.description: "Elanza-48: Tourism Management System, Spring-boot"
      org.opencontainers.image.authors: "Rajarshi Kundu <elanza48@outlook.com>"